

title: alisya teriana
email: alisyateriana47@gmail.com
description: I'm alisya teriana, i am from ACEH TANGGARA.I am currently living in the dormitory of the Lhokseumawe State Polytechnic.
url: "https://alisyateriana.github.io/"

plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag